;;; micromamba-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from micromamba.el

(autoload 'micromamba-activate "micromamba" "\
Switch to environment with PREFIX (path).  Prompt if called interactively.

If some environments have duplicate names, these names are replaced by
full paths.

(fn PREFIX)" t)
(autoload 'micromamba-deactivate "micromamba" "\
Deactivate the current environment." t)
(autoload 'micromamba-env-activate-for-buffer "micromamba" "\
Activate the conda environment implied by the current buffer.

This can be set by a buffer-local or project-local variable (e.g. a
`.dir-locals.el` that defines `conda-project-env-path`), or inferred from an
`environment.yml` or similar at the project level." t)
(defvar micromamba-env-autoactivate-mode nil "\
Non-nil if Micromamba-Env-Autoactivate mode is enabled.
See the `micromamba-env-autoactivate-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `micromamba-env-autoactivate-mode'.")
(custom-autoload 'micromamba-env-autoactivate-mode "micromamba" nil)
(autoload 'micromamba-env-autoactivate-mode "micromamba" "\
Toggle conda-env-autoactivate mode.

This mode automatically tries to activate a conda environment for the current
buffer.

This is a global minor mode.  If called interactively, toggle the
`Micromamba-Env-Autoactivate mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable the
mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='micromamba-env-autoactivate-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "micromamba" '("micromamba-"))

;;; End of scraped data

(provide 'micromamba-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; micromamba-autoloads.el ends here
