;;; load-theme-buffer-local-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from load-theme-buffer-local.el

(autoload 'load-theme-buffer-local "load-theme-buffer-local" "\
Load an Emacs24 THEME only in BUFFER.

(fn THEME &optional BUFFER NO-CONFIRM NO-ENABLE)" t)
(register-definition-prefixes "load-theme-buffer-local" '("custom-theme-buffer-local-"))

;;; End of scraped data

(provide 'load-theme-buffer-local-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; load-theme-buffer-local-autoloads.el ends here
