;;; visible-mark-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from visible-mark.el

(autoload 'visible-mark-mode "visible-mark" "\
A mode to make the mark visible.

This is a minor mode.  If called interactively, toggle the
`Visible-Mark mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `visible-mark-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(put 'global-visible-mark-mode 'globalized-minor-mode t)
(defvar global-visible-mark-mode nil "\
Non-nil if Global Visible-Mark mode is enabled.
See the `global-visible-mark-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-visible-mark-mode'.")
(custom-autoload 'global-visible-mark-mode "visible-mark" nil)
(autoload 'global-visible-mark-mode "visible-mark" "\
Toggle Visible-Mark mode in all buffers.
With prefix ARG, enable Global Visible-Mark mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Visible-Mark mode is enabled in all buffers where
`visible-mark-mode-maybe' would do it.

See `visible-mark-mode' for more information on Visible-Mark mode.

(fn &optional ARG)" t)
(register-definition-prefixes "visible-mark" '("global-visible-mark-mode-exclude-alist" "visible-mark-"))

;;; End of scraped data

(provide 'visible-mark-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; visible-mark-autoloads.el ends here
