;;; moody-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from moody.el

(autoload 'moody-replace-mode-line-buffer-identification "moody" "\


(fn &optional REVERSE)" t)
(autoload 'moody-replace-sml/mode-line-buffer-identification "moody" "\


(fn &optional REVERSE)" t)
(autoload 'moody-replace-vc-mode "moody" "\


(fn &optional REVERSE)" t)
(register-definition-prefixes "moody" '("moody-"))

;;; End of scraped data

(provide 'moody-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; moody-autoloads.el ends here
